### ISSUE TITLE
Expressions with parentheses

### ISSUE THREAD

**Issue by luizhf42** [AugustoRavazoli/react-calculator#1]
When a parentheses operation comes first in the expression, it always results in 0.

**Examples:**
- (5 + 5) * 2
- (8 - 4) * 2
- (10 - 2) / 4
- (5 + 5) + 5

However, in expressions that the parentheses are in another place, the calculation occurs properly.

**Ex.:**
- 2 * (5 + 5)
- 2 * (8 - 4)
- 4 / (10 - 8)
- 5 + (5 + 5)

**Comment by AugustoRavazoli** [comment]
Hello Luizhf42, thanks for reporting this bug to me. I run the test suit again and no erros occurred, then i'm thought the problem was in the UI, so i check this and i was right. The App.js puts a white space in the start of the string that is calculed, this caused this bug. I removed this white space, also thanks for reporting and feel free to use my app again, cya.
